Setup pre coomit hooks
antonije-pavlovic/raidensoft-project-boilerplate pull request #2
Opened 2022-08-23 20:01 UTC by antonije-pavlovic

2022-08-24 07:17 UTC, ljtupara requested changes

2022-08-24 07:17 UTC, ljtupara commented on README.md
> +pip install pre-commit
DOes this mean that now we need to install python for our projects?

2022-08-24 09:17 UTC, antonije-pavlovic commented on README.md
> +pip install pre-commit
No, this package can be installed via a system package manager (e.g brew for mac), for Linux it can be installed with snapd, but since the Linux kernel is shipped by default with python, we are using a python package manager to install it.

2022-08-24 09:29 UTC, ljtupara commented on README.md
> +pip install pre-commit
I have install it and test it. I have a problem when code is not ok hook reports problem, but linter fix it. So it is hard to deduce why linter failed.

2022-08-25 08:11 UTC, ljtupara approved these changes

2022-08-25 14:28 UTC, merged